version: "3.9"

services:
  postgres:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 9999:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: piotr@pipi.pl
      PGADMIN_DEFAULT_PASSWORD: piotr
    ports:
      - "7999:80"
    links:
      - "postgres"
