export const timezoneOptions = {
  Europe: [
    { name: 'Albania - Tirane', value: 'Europe/Tirane' },
    { name: 'Andorra', value: 'Europe/Andorra' },
    { name: 'Austria - Vienna', value: 'Europe/Vienna' },
    { name: 'Belarus - Minsk', value: 'Europe/Minsk' },
    { name: 'Belgium - Brussels', value: 'Europe/Brussels' },
    { name: 'Bulgaria - Sofia', value: 'Europe/Sofia' },
    { name: 'Czech Republic - Prague', value: 'Europe/Prague' },
    { name: 'Estonia - Tallinn', value: 'Europe/Tallinn' },
    { name: 'Finland - Helsinki', value: 'Europe/Helsinki' },
    { name: 'France - Paris', value: 'Europe/Paris' },
    { name: 'Germany - Berlin', value: 'Europe/Berlin' },
    { name: 'Gibraltar', value: 'Europe/Gibraltar' },
    { name: 'Greece - Athens', value: 'Europe/Athens' },
    { name: 'Hungary - Budapest', value: 'Europe/Budapest' },
    { name: 'Ireland - Dublin', value: 'Europe/Dublin' },
    { name: 'Italy - Rome', value: 'Europe/Rome' },
    { name: 'Latvia - Riga', value: 'Europe/Riga' },
    { name: 'Lithuania - Vilnius', value: 'Europe/Vilnius' },
    { name: 'Malta', value: 'Europe/Malta' },
    { name: 'Moldova - Chisinau', value: 'Europe/Chisinau' },
    { name: 'Poland - Warsaw', value: 'Europe/Warsaw' },
    { name: 'Portugal - Lisbon', value: 'Europe/Lisbon' },
    { name: 'Romania - Bucharest', value: 'Europe/Bucharest' },
    { name: 'Russia - Astrakhan', value: 'Europe/Astrakhan' },
    { name: 'Russia - Kaliningrad', value: 'Europe/Kaliningrad' },
    { name: 'Russia - Kirov', value: 'Europe/Kirov' },
    { name: 'Russia - Moscow', value: 'Europe/Moscow' },
    { name: 'Russia - Samara', value: 'Europe/Samara' },
    { name: 'Russia - Saratov', value: 'Europe/Saratov' },
    { name: 'Russia - Simferopol', value: 'Europe/Simferopol' },
    { name: 'Russia - Ulyanovsk', value: 'Europe/Ulyanovsk' },
    { name: 'Russia - Volgograd', value: 'Europe/Volgograd' },
    { name: 'Serbia - Belgrade', value: 'Europe/Belgrade' },
    { name: 'Spain - Madrid', value: 'Europe/Madrid' },
    { name: 'Switzerland - Zurich', value: 'Europe/Zurich' },
    { name: 'Turkey - Istanbul', value: 'Europe/Istanbul' },
    { name: 'Ukraine - Kyiv', value: 'Europe/Kyiv' },
    { name: 'United Kingdom - London', value: 'Europe/London' },
  ],
  America: [
    {
      name: 'Argentina - Buenos Aires',
      value: 'America/Argentina/Buenos_Aires',
    },
    { name: 'Argentina - Catamarca', value: 'America/Argentina/Catamarca' },
    { name: 'Argentina - Cordoba', value: 'America/Argentina/Cordoba' },
    { name: 'Argentina - Jujuy', value: 'America/Argentina/Jujuy' },
    { name: 'Argentina - La Rioja', value: 'America/Argentina/La_Rioja' },
    { name: 'Argentina - Mendoza', value: 'America/Argentina/Mendoza' },
    {
      name: 'Argentina - Rio Gallegos',
      value: 'America/Argentina/Rio_Gallegos',
    },
    { name: 'Argentina - Salta', value: 'America/Argentina/Salta' },
    { name: 'Argentina - San Juan', value: 'America/Argentina/San_Juan' },
    { name: 'Argentina - San Luis', value: 'America/Argentina/San_Luis' },
    { name: 'Argentina - Tucuman', value: 'America/Argentina/Tucuman' },
    { name: 'Argentina - Ushuaia', value: 'America/Argentina/Ushuaia' },
    { name: 'Barbados', value: 'America/Barbados' },
    { name: 'Belize', value: 'America/Belize' },
    { name: 'Bolivia - La Paz', value: 'America/La_Paz' },
    { name: 'Brazil - Araguaina', value: 'America/Araguaina' },
    { name: 'Brazil - Bahia', value: 'America/Bahia' },
    { name: 'Brazil - Belem', value: 'America/Belem' },
    { name: 'Brazil - Boa Vista', value: 'America/Boa_Vista' },
    { name: 'Brazil - Campo Grande', value: 'America/Campo_Grande' },
    { name: 'Brazil - Cuiaba', value: 'America/Cuiaba' },
    { name: 'Brazil - Eirunepe', value: 'America/Eirunepe' },
    { name: 'Brazil - Fortaleza', value: 'America/Fortaleza' },
    { name: 'Brazil - Maceio', value: 'America/Maceio' },
    { name: 'Brazil - Manaus', value: 'America/Manaus' },
    { name: 'Brazil - Noronha', value: 'America/Noronha' },
    { name: 'Brazil - Porto Velho', value: 'America/Porto_Velho' },
    { name: 'Brazil - Recife', value: 'America/Recife' },
    { name: 'Brazil - Rio Branco', value: 'America/Rio_Branco' },
    { name: 'Brazil - Santarem', value: 'America/Santarem' },
    { name: 'Brazil - Sao Paulo', value: 'America/Sao_Paulo' },
    { name: 'Canada - Cambridge Bay', value: 'America/Cambridge_Bay' },
    { name: 'Canada - Dawson', value: 'America/Dawson' },
    { name: 'Canada - Dawson Creek', value: 'America/Dawson_Creek' },
    { name: 'Canada - Edmonton', value: 'America/Edmonton' },
    { name: 'Canada - Fort Nelson', value: 'America/Fort_Nelson' },
    { name: 'Canada - Glace Bay', value: 'America/Glace_Bay' },
    { name: 'Canada - Goose Bay', value: 'America/Goose_Bay' },
    { name: 'Canada - Halifax', value: 'America/Halifax' },
    { name: 'Canada - Inuvik', value: 'America/Inuvik' },
    { name: 'Canada - Iqaluit', value: 'America/Iqaluit' },
    { name: 'Canada - Moncton', value: 'America/Moncton' },
    { name: 'Canada - Rankin Inlet', value: 'America/Rankin_Inlet' },
    { name: 'Canada - Regina', value: 'America/Regina' },
    { name: 'Canada - Resolute', value: 'America/Resolute' },
    { name: 'Canada - St Johns', value: 'America/St_Johns' },
    { name: 'Canada - Swift Current', value: 'America/Swift_Current' },
    { name: 'Canada - Toronto', value: 'America/Toronto' },
    { name: 'Canada - Vancouver', value: 'America/Vancouver' },
    { name: 'Canada - Whitehorse', value: 'America/Whitehorse' },
    { name: 'Canada - Winnipeg', value: 'America/Winnipeg' },
    { name: 'Canada - Yellowknife', value: 'America/Yellowknife' },
    { name: 'Chile - Punta Arenas', value: 'America/Punta_Arenas' },
    { name: 'Chile - Santiago', value: 'America/Santiago' },
    { name: 'Colombia - Bogota', value: 'America/Bogota' },
    { name: 'Costa Rica', value: 'America/Costa_Rica' },
    { name: 'Cuba - Havana', value: 'America/Havana' },
    {
      name: 'Dominican Republic - Santo Domingo',
      value: 'America/Santo_Domingo',
    },
    { name: 'Ecuador - Guayaquil', value: 'America/Guayaquil' },
    { name: 'El Salvador', value: 'America/El_Salvador' },
    { name: 'French Guiana - Cayenne', value: 'America/Cayenne' },
    { name: 'Greenland - Danmarkshavn', value: 'America/Danmarkshavn' },
    { name: 'Greenland - Nuuk', value: 'America/Nuuk' },
    { name: 'Greenland - Scoresbysund', value: 'America/Scoresbysund' },
    { name: 'Greenland - Thule', value: 'America/Thule' },
    { name: 'Guatemala', value: 'America/Guatemala' },
    { name: 'Guyana', value: 'America/Guyana' },
    { name: 'Haiti - Port-au-Prince', value: 'America/Port-au-Prince' },
    { name: 'Honduras - Tegucigalpa', value: 'America/Tegucigalpa' },
    { name: 'Jamaica', value: 'America/Jamaica' },
    { name: 'Martinique', value: 'America/Martinique' },
    { name: 'Mexico - Bahia Banderas', value: 'America/Bahia_Banderas' },
    { name: 'Mexico - Cancun', value: 'America/Cancun' },
    { name: 'Mexico - Chihuahua', value: 'America/Chihuahua' },
    { name: 'Mexico - Hermosillo', value: 'America/Hermosillo' },
    { name: 'Mexico - Matamoros', value: 'America/Matamoros' },
    { name: 'Mexico - Mazatlan', value: 'America/Mazatlan' },
    { name: 'Mexico - Merida', value: 'America/Merida' },
    { name: 'Mexico - Mexico City', value: 'America/Mexico_City' },
    { name: 'Mexico - Monterrey', value: 'America/Monterrey' },
    { name: 'Mexico - Ojinaga', value: 'America/Ojinaga' },
    { name: 'Mexico - Tijuana', value: 'America/Tijuana' },
    { name: 'Nicaragua - Managua', value: 'America/Managua' },
    { name: 'Panama', value: 'America/Panama' },
    { name: 'Paraguay - Asuncion', value: 'America/Asuncion' },
    { name: 'Peru - Lima', value: 'America/Lima' },
    { name: 'Puerto Rico', value: 'America/Puerto_Rico' },
    { name: 'Saint Pierre and Miquelon - Miquelon', value: 'America/Miquelon' },
    { name: 'Suriname - Paramaribo', value: 'America/Paramaribo' },
    {
      name: 'Turks and Caicos Islands - Grand Turk',
      value: 'America/Grand_Turk',
    },
    { name: 'United States - Adak', value: 'America/Adak' },
    { name: 'United States - Anchorage', value: 'America/Anchorage' },
    { name: 'United States - Beulah', value: 'America/North_Dakota/Beulah' },
    { name: 'United States - Boise', value: 'America/Boise' },
    { name: 'United States - Center', value: 'America/North_Dakota/Center' },
    { name: 'United States - Chicago', value: 'America/Chicago' },
    { name: 'United States - Denver', value: 'America/Denver' },
    { name: 'United States - Detroit', value: 'America/Detroit' },
    {
      name: 'United States - Indianapolis',
      value: 'America/Indiana/Indianapolis',
    },
    { name: 'United States - Juneau', value: 'America/Juneau' },
    { name: 'United States - Knox', value: 'America/Indiana/Knox' },
    { name: 'United States - Los Angeles', value: 'America/Los_Angeles' },
    {
      name: 'United States - Louisville',
      value: 'America/Kentucky/Louisville',
    },
    { name: 'United States - Marengo', value: 'America/Indiana/Marengo' },
    { name: 'United States - Menominee', value: 'America/Menominee' },
    { name: 'United States - Metlakatla', value: 'America/Metlakatla' },
    {
      name: 'United States - Monticello',
      value: 'America/Kentucky/Monticello',
    },
    {
      name: 'United States - New Salem',
      value: 'America/North_Dakota/New_Salem',
    },
    { name: 'United States - New York', value: 'America/New_York' },
    { name: 'United States - Nome', value: 'America/Nome' },
    { name: 'United States - Petersburg', value: 'America/Indiana/Petersburg' },
    { name: 'United States - Phoenix', value: 'America/Phoenix' },
    { name: 'United States - Sitka', value: 'America/Sitka' },
    { name: 'United States - Tell City', value: 'America/Indiana/Tell_City' },
    { name: 'United States - Vevay', value: 'America/Indiana/Vevay' },
    { name: 'United States - Vincennes', value: 'America/Indiana/Vincennes' },
    { name: 'United States - Winamac', value: 'America/Indiana/Winamac' },
    { name: 'United States - Yakutat', value: 'America/Yakutat' },
    { name: 'Uruguay - Montevideo', value: 'America/Montevideo' },
    { name: 'Venezuela - Caracas', value: 'America/Caracas' },
  ],
  Australia: [
    { name: 'Adelaide', value: 'Australia/Adelaide' },
    { name: 'Brisbane', value: 'Australia/Brisbane' },
    { name: 'Broken Hill', value: 'Australia/Broken_Hill' },
    { name: 'Darwin', value: 'Australia/Darwin' },
    { name: 'Eucla', value: 'Australia/Eucla' },
    { name: 'Hobart', value: 'Australia/Hobart' },
    { name: 'Lindeman', value: 'Australia/Lindeman' },
    { name: 'Lord Howe', value: 'Australia/Lord_Howe' },
    { name: 'Melbourne', value: 'Australia/Melbourne' },
    { name: 'Perth', value: 'Australia/Perth' },
    { name: 'Sydney', value: 'Australia/Sydney' },
  ],
  Asia: [
    { name: 'Kabul', value: 'Asia/Kabul' },
    { name: 'Yerevan', value: 'Asia/Yerevan' },
    { name: 'Baku', value: 'Asia/Baku' },
    { name: 'Dhaka', value: 'Asia/Dhaka' },
    { name: 'Thimphu', value: 'Asia/Thimphu' },
    { name: 'Yangon', value: 'Asia/Yangon' },
    { name: 'Shanghai', value: 'Asia/Shanghai' },
    { name: 'Urumqi', value: 'Asia/Urumqi' },
    { name: 'Hong Kong', value: 'Asia/Hong_Kong' },
    { name: 'Taipei', value: 'Asia/Taipei' },
    { name: 'Macau', value: 'Asia/Macau' },
    { name: 'Nicosia', value: 'Asia/Nicosia' },
    { name: 'Famagusta', value: 'Asia/Famagusta' },
    { name: 'Tbilisi', value: 'Asia/Tbilisi' },
    { name: 'Dili', value: 'Asia/Dili' },
    { name: 'Kolkata', value: 'Asia/Kolkata' },
    { name: 'Jakarta', value: 'Asia/Jakarta' },
    { name: 'Pontianak', value: 'Asia/Pontianak' },
    { name: 'Makassar', value: 'Asia/Makassar' },
    { name: 'Jayapura', value: 'Asia/Jayapura' },
    { name: 'Tehran', value: 'Asia/Tehran' },
    { name: 'Baghdad', value: 'Asia/Baghdad' },
    { name: 'Jerusalem', value: 'Asia/Jerusalem' },
    { name: 'Tokyo', value: 'Asia/Tokyo' },
    { name: 'Amman', value: 'Asia/Amman' },
    { name: 'Almaty', value: 'Asia/Almaty' },
    { name: 'Qyzylorda', value: 'Asia/Qyzylorda' },
    { name: 'Qostanay', value: 'Asia/Qostanay' },
    { name: 'Aqtobe', value: 'Asia/Aqtobe' },
    { name: 'Aqtau', value: 'Asia/Aqtau' },
    { name: 'Atyrau', value: 'Asia/Atyrau' },
    { name: 'Oral', value: 'Asia/Oral' },
    { name: 'Bishkek', value: 'Asia/Bishkek' },
    { name: 'Seoul', value: 'Asia/Seoul' },
    { name: 'Pyongyang', value: 'Asia/Pyongyang' },
    { name: 'Beirut', value: 'Asia/Beirut' },
    { name: 'Kuching', value: 'Asia/Kuching' },
    { name: 'Hovd', value: 'Asia/Hovd' },
    { name: 'Ulaanbaatar', value: 'Asia/Ulaanbaatar' },
    { name: 'Choibalsan', value: 'Asia/Choibalsan' },
    { name: 'Kathmandu', value: 'Asia/Kathmandu' },
    { name: 'Karachi', value: 'Asia/Karachi' },
    { name: 'Gaza', value: 'Asia/Gaza' },
    { name: 'Hebron', value: 'Asia/Hebron' },
    { name: 'Manila', value: 'Asia/Manila' },
    { name: 'Qatar', value: 'Asia/Qatar' },
    { name: 'Riyadh', value: 'Asia/Riyadh' },
    { name: 'Singapore', value: 'Asia/Singapore' },
    { name: 'Colombo', value: 'Asia/Colombo' },
    { name: 'Damascus', value: 'Asia/Damascus' },
    { name: 'Dushanbe', value: 'Asia/Dushanbe' },
    { name: 'Bangkok', value: 'Asia/Bangkok' },
    { name: 'Ashgabat', value: 'Asia/Ashgabat' },
    { name: 'Dubai', value: 'Asia/Dubai' },
    { name: 'Samarkand', value: 'Asia/Samarkand' },
    { name: 'Tashkent', value: 'Asia/Tashkent' },
    { name: 'Ho Chi Minh', value: 'Asia/Ho_Chi_Minh' },
    { name: 'Yekaterinburg', value: 'Asia/Yekaterinburg' },
    { name: 'Omsk', value: 'Asia/Omsk' },
    { name: 'Barnaul', value: 'Asia/Barnaul' },
    { name: 'Novosibirsk', value: 'Asia/Novosibirsk' },
    { name: 'Tomsk', value: 'Asia/Tomsk' },
    { name: 'Novokuznetsk', value: 'Asia/Novokuznetsk' },
    { name: 'Krasnoyarsk', value: 'Asia/Krasnoyarsk' },
    { name: 'Irkutsk', value: 'Asia/Irkutsk' },
    { name: 'Chita', value: 'Asia/Chita' },
    { name: 'Yakutsk', value: 'Asia/Yakutsk' },
    { name: 'Vladivostok', value: 'Asia/Vladivostok' },
    { name: 'Khandyga', value: 'Asia/Khandyga' },
    { name: 'Sakhalin', value: 'Asia/Sakhalin' },
    { name: 'Magadan', value: 'Asia/Magadan' },
    { name: 'Srednekolymsk', value: 'Asia/Srednekolymsk' },
    { name: 'Ust-Nera', value: 'Asia/Ust-Nera' },
    { name: 'Kamchatka', value: 'Asia/Kamchatka' },
    { name: 'Anadyr', value: 'Asia/Anadyr' },
  ],
  Africa: [
    { name: 'Algiers', value: 'Africa/Algiers' },
    { name: 'Ndjamena', value: 'Africa/Ndjamena' },
    { name: 'Abidjan', value: 'Africa/Abidjan' },
    { name: 'Cairo', value: 'Africa/Cairo' },
    { name: 'Bissau', value: 'Africa/Bissau' },
    { name: 'Nairobi', value: 'Africa/Nairobi' },
    { name: 'Monrovia', value: 'Africa/Monrovia' },
    { name: 'Tripoli', value: 'Africa/Tripoli' },
    { name: 'Casablanca', value: 'Africa/Casablanca' },
    { name: 'El Aaiun', value: 'Africa/El_Aaiun' },
    { name: 'Maputo', value: 'Africa/Maputo' },
    { name: 'Windhoek', value: 'Africa/Windhoek' },
    { name: 'Lagos', value: 'Africa/Lagos' },
    { name: 'Sao Tome', value: 'Africa/Sao_Tome' },
    { name: 'Johannesburg', value: 'Africa/Johannesburg' },
    { name: 'Khartoum', value: 'Africa/Khartoum' },
    { name: 'Juba', value: 'Africa/Juba' },
    { name: 'Tunis', value: 'Africa/Tunis' },
    { name: 'Ceuta', value: 'Africa/Ceuta' },
  ],
  Atlantic: [
    { name: 'Cape Verde', value: 'Atlantic/Cape_Verde' },
    { name: 'Faroe', value: 'Atlantic/Faroe' },
    { name: 'Azores', value: 'Atlantic/Azores' },
    { name: 'Madeira', value: 'Atlantic/Madeira' },
    { name: 'Canary', value: 'Atlantic/Canary' },
    { name: 'Bermuda', value: 'Atlantic/Bermuda' },
    { name: 'Stanley', value: 'Atlantic/Stanley' },
    { name: 'South Georgia', value: 'Atlantic/South_Georgia' },
  ],
  Indian: [
    { name: 'Mauritius', value: 'Indian/Mauritius' },
    { name: 'Chagos', value: 'Indian/Chagos' },
    { name: 'Maldives', value: 'Indian/Maldives' },
  ],
  Antarctica: [
    { name: 'Casey', value: 'Antarctica/Casey' },
    { name: 'Davis', value: 'Antarctica/Davis' },
    { name: 'Mawson', value: 'Antarctica/Mawson' },
    { name: 'Troll', value: 'Antarctica/Troll' },
    { name: 'Rothera', value: 'Antarctica/Rothera' },
    { name: 'Macquarie', value: 'Antarctica/Macquarie' },
    { name: 'Palmer', value: 'Antarctica/Palmer' },
  ],
  Pacific: [
    { name: 'Fiji', value: 'Pacific/Fiji' },
    { name: 'Gambier', value: 'Pacific/Gambier' },
    { name: 'Marquesas', value: 'Pacific/Marquesas' },
    { name: 'Tahiti', value: 'Pacific/Tahiti' },
    { name: 'Guam', value: 'Pacific/Guam' },
    { name: 'Tarawa', value: 'Pacific/Tarawa' },
    { name: 'Kanton', value: 'Pacific/Kanton' },
    { name: 'Kiritimati', value: 'Pacific/Kiritimati' },
    { name: 'Kwajalein', value: 'Pacific/Kwajalein' },
    { name: 'Kosrae', value: 'Pacific/Kosrae' },
    { name: 'Nauru', value: 'Pacific/Nauru' },
    { name: 'Noumea', value: 'Pacific/Noumea' },
    { name: 'Auckland', value: 'Pacific/Auckland' },
    { name: 'Chatham', value: 'Pacific/Chatham' },
    { name: 'Rarotonga', value: 'Pacific/Rarotonga' },
    { name: 'Niue', value: 'Pacific/Niue' },
    { name: 'Norfolk', value: 'Pacific/Norfolk' },
    { name: 'Palau', value: 'Pacific/Palau' },
    { name: 'Port Moresby', value: 'Pacific/Port_Moresby' },
    { name: 'Bougainville', value: 'Pacific/Bougainville' },
    { name: 'Pitcairn', value: 'Pacific/Pitcairn' },
    { name: 'Pago Pago', value: 'Pacific/Pago_Pago' },
    { name: 'Apia', value: 'Pacific/Apia' },
    { name: 'Guadalcanal', value: 'Pacific/Guadalcanal' },
    { name: 'Fakaofo', value: 'Pacific/Fakaofo' },
    { name: 'Tongatapu', value: 'Pacific/Tongatapu' },
    { name: 'Efate', value: 'Pacific/Efate' },
    { name: 'Honolulu', value: 'Pacific/Honolulu' },
    { name: 'Easter', value: 'Pacific/Easter' },
    { name: 'Galapagos', value: 'Pacific/Galapagos' },
  ],
  Etc: [
    { name: 'UTC', value: 'Etc/UTC' },
    { name: 'GMT', value: 'Etc/GMT' },
    { name: 'GMT-14', value: 'Etc/GMT-14' },
    { name: 'GMT-13', value: 'Etc/GMT-13' },
    { name: 'GMT-12', value: 'Etc/GMT-12' },
    { name: 'GMT-11', value: 'Etc/GMT-11' },
    { name: 'GMT-10', value: 'Etc/GMT-10' },
    { name: 'GMT-9', value: 'Etc/GMT-9' },
    { name: 'GMT-8', value: 'Etc/GMT-8' },
    { name: 'GMT-7', value: 'Etc/GMT-7' },
    { name: 'GMT-6', value: 'Etc/GMT-6' },
    { name: 'GMT-5', value: 'Etc/GMT-5' },
    { name: 'GMT-4', value: 'Etc/GMT-4' },
    { name: 'GMT-3', value: 'Etc/GMT-3' },
    { name: 'GMT-2', value: 'Etc/GMT-2' },
    { name: 'GMT-1', value: 'Etc/GMT-1' },
    { name: 'GMT+1', value: 'Etc/GMT+1' },
    { name: 'GMT+2', value: 'Etc/GMT+2' },
    { name: 'GMT+3', value: 'Etc/GMT+3' },
    { name: 'GMT+4', value: 'Etc/GMT+4' },
    { name: 'GMT+5', value: 'Etc/GMT+5' },
    { name: 'GMT+6', value: 'Etc/GMT+6' },
    { name: 'GMT+7', value: 'Etc/GMT+7' },
    { name: 'GMT+8', value: 'Etc/GMT+8' },
    { name: 'GMT+9', value: 'Etc/GMT+9' },
    { name: 'GMT+10', value: 'Etc/GMT+10' },
    { name: 'GMT+11', value: 'Etc/GMT+11' },
    { name: 'GMT+12', value: 'Etc/GMT+12' },
  ],
  Other: [
    { name: 'WET', value: 'WET' },
    { name: 'CET', value: 'CET' },
    { name: 'MET', value: 'MET' },
    { name: 'EET', value: 'EET' },
    { name: 'Factory', value: 'Factory' },
    { name: 'EST', value: 'EST' },
    { name: 'MST', value: 'MST' },
    { name: 'HST', value: 'HST' },
    { name: 'EST5EDT', value: 'EST5EDT' },
    { name: 'CST6CDT', value: 'CST6CDT' },
    { name: 'MST7MDT', value: 'MST7MDT' },
    { name: 'PST8PDT', value: 'PST8PDT' },
  ],
};
