export const timezoneOptions = {
  Other: [
    { name: 'WET', value: 'WET' },
    { name: 'CET', value: 'CET' },
    { name: 'MET', value: 'MET' },
    { name: 'EET', value: 'EET' },
    { name: 'Factory', value: 'Factory' },
    { name: 'EST', value: 'EST' },
    { name: 'MST', value: 'MST' },
    { name: 'HST', value: 'HST' },
    { name: 'EST5EDT', value: 'EST5EDT' },
    { name: 'CST6CDT', value: 'CST6CDT' },
    { name: 'MST7MDT', value: 'MST7MDT' },
    { name: 'PST8PDT', value: 'PST8PDT' },
  ],
  Africa: [
    { name: 'Algeria - Algiers', value: 'Africa/Algiers' },
    { name: 'Ndjamena', value: 'Africa/Ndjamena' },
    { name: "Cote D'Ivoire (Ivory Coast) - Abidjan", value: 'Africa/Abidjan' },
    { name: 'Egypt - Cairo', value: 'Africa/Cairo' },
    { name: 'India - Bissau', value: 'Africa/Bissau' },
    { name: 'Kenya - Nairobi', value: 'Africa/Nairobi' },
    { name: 'Liberia - Monrovia', value: 'Africa/Monrovia' },
    { name: 'Lebanon - Tripoli', value: 'Africa/Tripoli' },
    { name: 'Chile - Casablanca', value: 'Africa/Casablanca' },
    { name: 'El Aaiun', value: 'Africa/El_Aaiun' },
    { name: 'Mozambique - Maputo', value: 'Africa/Maputo' },
    { name: 'Namibia - Windhoek', value: 'Africa/Windhoek' },
    { name: 'Nigeria - Lagos', value: 'Africa/Lagos' },
    { name: 'Sao Tome', value: 'Africa/Sao_Tome' },
    { name: 'South Africa - Johannesburg', value: 'Africa/Johannesburg' },
    { name: 'Sudan - Khartoum', value: 'Africa/Khartoum' },
    { name: 'Juba', value: 'Africa/Juba' },
    { name: 'Tunisia - Tunis', value: 'Africa/Tunis' },
    { name: 'Spain - Ceuta', value: 'Africa/Ceuta' },
  ],
  Atlantic: [
    { name: 'Cape Verde', value: 'Atlantic/Cape_Verde' },
    { name: 'Faroe', value: 'Atlantic/Faroe' },
    { name: 'Azores', value: 'Atlantic/Azores' },
    { name: 'United States - Madeira', value: 'Atlantic/Madeira' },
    { name: 'Canary', value: 'Atlantic/Canary' },
    { name: 'Bermuda', value: 'Atlantic/Bermuda' },
    { name: 'United Kingdom - Stanley', value: 'Atlantic/Stanley' },
    { name: 'South Georgia', value: 'Atlantic/South_Georgia' },
  ],
  Indian: [
    { name: 'Mauritius', value: 'Indian/Mauritius' },
    { name: 'Chagos', value: 'Indian/Chagos' },
    { name: 'Maldives', value: 'Indian/Maldives' },
  ],
  Antarctica: [
    { name: 'Australia - Casey', value: 'Antarctica/Casey' },
    { name: 'United States - Davis', value: 'Antarctica/Davis' },
    { name: 'Australia - Mawson', value: 'Antarctica/Mawson' },
    { name: 'Troll', value: 'Antarctica/Troll' },
    { name: 'Rothera', value: 'Antarctica/Rothera' },
    { name: 'Australia - Macquarie', value: 'Antarctica/Macquarie' },
    { name: 'United States - Palmer', value: 'Antarctica/Palmer' },
  ],
  Asia: [
    { name: 'Afghanistan - Kabul', value: 'Asia/Kabul' },
    { name: 'Armenia - Yerevan', value: 'Asia/Yerevan' },
    { name: 'Azerbaijan - Baku', value: 'Asia/Baku' },
    { name: 'Bangladesh - Dhaka', value: 'Asia/Dhaka' },
    { name: 'Bhutan - Thimphu', value: 'Asia/Thimphu' },
    { name: 'Myanmar - Yangon', value: 'Asia/Yangon' },
    { name: 'China - Shanghai', value: 'Asia/Shanghai' },
    { name: 'Urumqi', value: 'Asia/Urumqi' },
    { name: 'Hong Kong', value: 'Asia/Hong_Kong' },
    { name: 'Taiwan - Taipei', value: 'Asia/Taipei' },
    { name: 'Brazil - Macau', value: 'Asia/Macau' },
    { name: 'Cyprus - Nicosia', value: 'Asia/Nicosia' },
    { name: 'Cyprus - Famagusta', value: 'Asia/Famagusta' },
    { name: 'Georgia - Tbilisi', value: 'Asia/Tbilisi' },
    { name: 'East Timor - Dili', value: 'Asia/Dili' },
    { name: 'India - Kolkata', value: 'Asia/Kolkata' },
    { name: 'Indonesia - Jakarta', value: 'Asia/Jakarta' },
    { name: 'Pontianak', value: 'Asia/Pontianak' },
    { name: 'Indonesia - Makassar', value: 'Asia/Makassar' },
    { name: 'Indonesia - Jayapura', value: 'Asia/Jayapura' },
    { name: 'Iran - Tehran', value: 'Asia/Tehran' },
    { name: 'Iraq - Baghdad', value: 'Asia/Baghdad' },
    { name: 'Israel - Jerusalem', value: 'Asia/Jerusalem' },
    { name: 'Japan - Tokyo', value: 'Asia/Tokyo' },
    { name: 'Jordan - Amman', value: 'Asia/Amman' },
    { name: 'Kazakhstan - Almaty', value: 'Asia/Almaty' },
    { name: 'Qyzylorda', value: 'Asia/Qyzylorda' },
    { name: 'Qostanay', value: 'Asia/Qostanay' },
    { name: 'Aqtobe', value: 'Asia/Aqtobe' },
    { name: 'Aqtau', value: 'Asia/Aqtau' },
    { name: 'Kazakhstan - Atyrau', value: 'Asia/Atyrau' },
    { name: 'Kazakhstan - Oral', value: 'Asia/Oral' },
    { name: 'Kyrgyzstan - Bishkek', value: 'Asia/Bishkek' },
    { name: 'South Korea - Seoul', value: 'Asia/Seoul' },
    { name: 'North Korea - Pyongyang', value: 'Asia/Pyongyang' },
    { name: 'Lebanon - Beirut', value: 'Asia/Beirut' },
    { name: 'Malaysia - Kuching', value: 'Asia/Kuching' },
    { name: 'Mongolia - Hovd', value: 'Asia/Hovd' },
    { name: 'Ulaanbaatar', value: 'Asia/Ulaanbaatar' },
    { name: 'Mongolia - Choibalsan', value: 'Asia/Choibalsan' },
    { name: 'Nepal - Kathmandu', value: 'Asia/Kathmandu' },
    { name: 'Pakistan - Karachi', value: 'Asia/Karachi' },
    { name: 'Gaza', value: 'Asia/Gaza' },
    { name: 'United States - Hebron', value: 'Asia/Hebron' },
    { name: 'Philippines - Manila', value: 'Asia/Manila' },
    { name: 'Qatar', value: 'Asia/Qatar' },
    { name: 'Saudi Arabia - Riyadh', value: 'Asia/Riyadh' },
    { name: 'Singapore - Singapore', value: 'Asia/Singapore' },
    { name: 'Brazil - Colombo', value: 'Asia/Colombo' },
    { name: 'Syria - Damascus', value: 'Asia/Damascus' },
    { name: 'Dushanbe', value: 'Asia/Dushanbe' },
    { name: 'Thailand - Bangkok', value: 'Asia/Bangkok' },
    { name: 'Turkmenistan - Ashgabat', value: 'Asia/Ashgabat' },
    { name: 'United Arab Emirates - Dubai', value: 'Asia/Dubai' },
    { name: 'Uzbekistan - Samarkand', value: 'Asia/Samarkand' },
    { name: 'Uzbekistan - Tashkent', value: 'Asia/Tashkent' },
    { name: 'Ho Chi Minh', value: 'Asia/Ho_Chi_Minh' },
    { name: 'Russia - Yekaterinburg', value: 'Asia/Yekaterinburg' },
    { name: 'Russia - Omsk', value: 'Asia/Omsk' },
    { name: 'Russia - Barnaul', value: 'Asia/Barnaul' },
    { name: 'Russia - Novosibirsk', value: 'Asia/Novosibirsk' },
    { name: 'Russia - Tomsk', value: 'Asia/Tomsk' },
    { name: 'Russia - Novokuznetsk', value: 'Asia/Novokuznetsk' },
    { name: 'Russia - Krasnoyarsk', value: 'Asia/Krasnoyarsk' },
    { name: 'Russia - Irkutsk', value: 'Asia/Irkutsk' },
    { name: 'Colombia - Chita', value: 'Asia/Chita' },
    { name: 'Russia - Yakutsk', value: 'Asia/Yakutsk' },
    { name: 'Russia - Vladivostok', value: 'Asia/Vladivostok' },
    { name: 'Russia - Khandyga', value: 'Asia/Khandyga' },
    { name: 'Sakhalin', value: 'Asia/Sakhalin' },
    { name: 'Russia - Magadan', value: 'Asia/Magadan' },
    { name: 'Russia - Srednekolymsk', value: 'Asia/Srednekolymsk' },
    { name: 'Russia - Ust-Nera', value: 'Asia/Ust-Nera' },
    { name: 'Kamchatka', value: 'Asia/Kamchatka' },
    { name: 'Russia - Anadyr', value: 'Asia/Anadyr' },
  ],
  Australia: [
    { name: 'Argentina - Darwin', value: 'Australia/Darwin' },
    { name: 'Australia - Perth', value: 'Australia/Perth' },
    { name: 'Eucla', value: 'Australia/Eucla' },
    { name: 'Australia - Brisbane', value: 'Australia/Brisbane' },
    { name: 'Lindeman', value: 'Australia/Lindeman' },
    { name: 'Australia - Adelaide', value: 'Australia/Adelaide' },
    { name: 'Australia - Hobart', value: 'Australia/Hobart' },
    { name: 'Australia - Melbourne', value: 'Australia/Melbourne' },
    { name: 'Australia - Sydney', value: 'Australia/Sydney' },
    { name: 'Australia - Broken Hill', value: 'Australia/Broken_Hill' },
    { name: 'Lord Howe', value: 'Australia/Lord_Howe' },
  ],
  Pacific: [
    { name: 'Saudi Arabia - Fiji', value: 'Pacific/Fiji' },
    { name: 'United States - Gambier', value: 'Pacific/Gambier' },
    { name: 'Marquesas', value: 'Pacific/Marquesas' },
    { name: 'Tahiti', value: 'Pacific/Tahiti' },
    { name: 'Guam', value: 'Pacific/Guam' },
    { name: 'Kiribati - Tarawa', value: 'Pacific/Tarawa' },
    { name: 'Kiribati - Kanton', value: 'Pacific/Kanton' },
    { name: 'Kiribati - Kiritimati', value: 'Pacific/Kiritimati' },
    { name: 'Kwajalein', value: 'Pacific/Kwajalein' },
    { name: 'Kosrae', value: 'Pacific/Kosrae' },
    { name: 'Nauru', value: 'Pacific/Nauru' },
    { name: 'Noumea', value: 'Pacific/Noumea' },
    { name: 'New Zealand - Auckland', value: 'Pacific/Auckland' },
    { name: 'Canada - Chatham', value: 'Pacific/Chatham' },
    { name: 'Rarotonga', value: 'Pacific/Rarotonga' },
    { name: 'Niue', value: 'Pacific/Niue' },
    { name: 'United Kingdom - Norfolk', value: 'Pacific/Norfolk' },
    { name: 'Italy - Palau', value: 'Pacific/Palau' },
    { name: 'Papua new Guinea - Port Moresby', value: 'Pacific/Port_Moresby' },
    { name: 'Bougainville', value: 'Pacific/Bougainville' },
    { name: 'United States - Pitcairn', value: 'Pacific/Pitcairn' },
    { name: 'Pago Pago', value: 'Pacific/Pago_Pago' },
    { name: 'Samoa - Apia', value: 'Pacific/Apia' },
    { name: 'Spain - Guadalcanal', value: 'Pacific/Guadalcanal' },
    { name: 'Fakaofo', value: 'Pacific/Fakaofo' },
    { name: 'Tongatapu', value: 'Pacific/Tongatapu' },
    { name: 'Efate', value: 'Pacific/Efate' },
    { name: 'United States - Honolulu', value: 'Pacific/Honolulu' },
    { name: 'Easter', value: 'Pacific/Easter' },
    { name: 'Galapagos', value: 'Pacific/Galapagos' },
  ],
  Etc: [
    { name: 'UTC', value: 'Etc/UTC' },
    { name: 'GMT', value: 'Etc/GMT' },
    { name: 'GMT-14', value: 'Etc/GMT-14' },
    { name: 'GMT-13', value: 'Etc/GMT-13' },
    { name: 'GMT-12', value: 'Etc/GMT-12' },
    { name: 'GMT-11', value: 'Etc/GMT-11' },
    { name: 'GMT-10', value: 'Etc/GMT-10' },
    { name: 'GMT-9', value: 'Etc/GMT-9' },
    { name: 'GMT-8', value: 'Etc/GMT-8' },
    { name: 'GMT-7', value: 'Etc/GMT-7' },
    { name: 'GMT-6', value: 'Etc/GMT-6' },
    { name: 'GMT-5', value: 'Etc/GMT-5' },
    { name: 'GMT-4', value: 'Etc/GMT-4' },
    { name: 'GMT-3', value: 'Etc/GMT-3' },
    { name: 'GMT-2', value: 'Etc/GMT-2' },
    { name: 'GMT-1', value: 'Etc/GMT-1' },
    { name: 'GMT+1', value: 'Etc/GMT+1' },
    { name: 'GMT+2', value: 'Etc/GMT+2' },
    { name: 'GMT+3', value: 'Etc/GMT+3' },
    { name: 'GMT+4', value: 'Etc/GMT+4' },
    { name: 'GMT+5', value: 'Etc/GMT+5' },
    { name: 'GMT+6', value: 'Etc/GMT+6' },
    { name: 'GMT+7', value: 'Etc/GMT+7' },
    { name: 'GMT+8', value: 'Etc/GMT+8' },
    { name: 'GMT+9', value: 'Etc/GMT+9' },
    { name: 'GMT+10', value: 'Etc/GMT+10' },
    { name: 'GMT+11', value: 'Etc/GMT+11' },
    { name: 'GMT+12', value: 'Etc/GMT+12' },
  ],
  Europe: [
    { name: 'Canada - London', value: 'Europe/London' },
    { name: 'Ireland - Dublin', value: 'Europe/Dublin' },
    { name: 'Tirane', value: 'Europe/Tirane' },
    { name: 'Spain - Andorra', value: 'Europe/Andorra' },
    { name: 'Austria - Vienna', value: 'Europe/Vienna' },
    { name: 'Belarus - Minsk', value: 'Europe/Minsk' },
    { name: 'Belgium - Brussels', value: 'Europe/Brussels' },
    { name: 'Bulgaria - Sofia', value: 'Europe/Sofia' },
    { name: 'Czech Republic - Prague', value: 'Europe/Prague' },
    { name: 'Estonia - Tallinn', value: 'Europe/Tallinn' },
    { name: 'Finland - Helsinki', value: 'Europe/Helsinki' },
    { name: 'Canada - Paris', value: 'Europe/Paris' },
    { name: 'Germany - Berlin', value: 'Europe/Berlin' },
    { name: 'Jamaica - Gibraltar', value: 'Europe/Gibraltar' },
    { name: 'Greece - Athens', value: 'Europe/Athens' },
    { name: 'Hungary - Budapest', value: 'Europe/Budapest' },
    { name: 'Italy - Rome', value: 'Europe/Rome' },
    { name: 'Latvia - Riga', value: 'Europe/Riga' },
    { name: 'Lithuania - Vilnius', value: 'Europe/Vilnius' },
    { name: 'Austria - Malta', value: 'Europe/Malta' },
    { name: 'Moldova - Chisinau', value: 'Europe/Chisinau' },
    { name: 'Poland - Warsaw', value: 'Europe/Warsaw' },
    { name: 'Portugal - Lisbon', value: 'Europe/Lisbon' },
    { name: 'Romania - Bucharest', value: 'Europe/Bucharest' },
    { name: 'Russia - Kaliningrad', value: 'Europe/Kaliningrad' },
    { name: 'Russia - Moscow', value: 'Europe/Moscow' },
    { name: 'Ukraine - Simferopol', value: 'Europe/Simferopol' },
    { name: 'Kazakhstan - Astrakhan', value: 'Europe/Astrakhan' },
    { name: 'Russia - Volgograd', value: 'Europe/Volgograd' },
    { name: 'Russia - Saratov', value: 'Europe/Saratov' },
    { name: 'Russia - Kirov', value: 'Europe/Kirov' },
    { name: 'Russia - Samara', value: 'Europe/Samara' },
    { name: 'Russia - Ulyanovsk', value: 'Europe/Ulyanovsk' },
    { name: 'Serbia - Belgrade', value: 'Europe/Belgrade' },
    { name: 'Colombia - Madrid', value: 'Europe/Madrid' },
    { name: 'Zurich', value: 'Europe/Zurich' },
    { name: 'Istanbul', value: 'Europe/Istanbul' },
    { name: 'Ukraine - Kyiv', value: 'Europe/Kyiv' },
  ],
  America: [
    { name: 'Danmarkshavn', value: 'America/Danmarkshavn' },
    { name: 'Scoresbysund', value: 'America/Scoresbysund' },
    { name: 'Nuuk', value: 'America/Nuuk' },
    { name: 'Thule', value: 'America/Thule' },
    { name: 'New York', value: 'America/New_York' },
    { name: 'United States - Chicago', value: 'America/Chicago' },
    { name: 'United States - Center', value: 'America/North_Dakota/Center' },
    { name: 'New Salem', value: 'America/North_Dakota/New_Salem' },
    { name: 'United States - Beulah', value: 'America/North_Dakota/Beulah' },
    { name: 'United States - Denver', value: 'America/Denver' },
    { name: 'Mexico - Los Angeles', value: 'America/Los_Angeles' },
    { name: 'United States - Juneau', value: 'America/Juneau' },
    { name: 'United States - Sitka', value: 'America/Sitka' },
    { name: 'United States - Metlakatla', value: 'America/Metlakatla' },
    { name: 'Yakutat', value: 'America/Yakutat' },
    { name: 'United States - Anchorage', value: 'America/Anchorage' },
    { name: 'Australia - Nome', value: 'America/Nome' },
    { name: 'Adak', value: 'America/Adak' },
    { name: 'United States - Phoenix', value: 'America/Phoenix' },
    { name: 'United States - Boise', value: 'America/Boise' },
    {
      name: 'United States - Indianapolis',
      value: 'America/Indiana/Indianapolis',
    },
    { name: 'United States - Marengo', value: 'America/Indiana/Marengo' },
    { name: 'France - Vincennes', value: 'America/Indiana/Vincennes' },
    { name: 'United States - Tell City', value: 'America/Indiana/Tell_City' },
    { name: 'United States - Petersburg', value: 'America/Indiana/Petersburg' },
    { name: 'Australia - Knox', value: 'America/Indiana/Knox' },
    { name: 'United States - Winamac', value: 'America/Indiana/Winamac' },
    { name: 'United States - Vevay', value: 'America/Indiana/Vevay' },
    {
      name: 'United States - Louisville',
      value: 'America/Kentucky/Louisville',
    },
    { name: 'France - Monticello', value: 'America/Kentucky/Monticello' },
    { name: 'United States - Detroit', value: 'America/Detroit' },
    { name: 'United States - Menominee', value: 'America/Menominee' },
    { name: 'St Johns', value: 'America/St_Johns' },
    { name: 'Goose Bay', value: 'America/Goose_Bay' },
    { name: 'Canada - Halifax', value: 'America/Halifax' },
    { name: 'Canada - Glace Bay', value: 'America/Glace_Bay' },
    { name: 'Canada - Moncton', value: 'America/Moncton' },
    { name: 'Australia - Toronto', value: 'America/Toronto' },
    { name: 'Canada - Winnipeg', value: 'America/Winnipeg' },
    { name: 'Canada - Regina', value: 'America/Regina' },
    { name: 'Canada - Swift Current', value: 'America/Swift_Current' },
    { name: 'Australia - Edmonton', value: 'America/Edmonton' },
    { name: 'Canada - Vancouver', value: 'America/Vancouver' },
    { name: 'Canada - Dawson Creek', value: 'America/Dawson_Creek' },
    { name: 'Canada - Fort Nelson', value: 'America/Fort_Nelson' },
    { name: 'Canada - Iqaluit', value: 'America/Iqaluit' },
    { name: 'Resolute', value: 'America/Resolute' },
    { name: 'Canada - Rankin Inlet', value: 'America/Rankin_Inlet' },
    { name: 'Cambridge Bay', value: 'America/Cambridge_Bay' },
    { name: 'Canada - Yellowknife', value: 'America/Yellowknife' },
    { name: 'Canada - Inuvik', value: 'America/Inuvik' },
    { name: 'Australia - Whitehorse', value: 'America/Whitehorse' },
    { name: 'United States - Dawson', value: 'America/Dawson' },
    { name: 'Cancun', value: 'America/Cancun' },
    { name: 'Philippines - Merida', value: 'America/Merida' },
    { name: 'Mexico - Matamoros', value: 'America/Matamoros' },
    { name: 'Colombia - Monterrey', value: 'America/Monterrey' },
    { name: 'Mexico City', value: 'America/Mexico_City' },
    { name: 'Mexico - Ojinaga', value: 'America/Ojinaga' },
    { name: 'Mexico - Chihuahua', value: 'America/Chihuahua' },
    { name: 'Mexico - Hermosillo', value: 'America/Hermosillo' },
    { name: 'Mexico - Mazatlan', value: 'America/Mazatlan' },
    { name: 'Bahia Banderas', value: 'America/Bahia_Banderas' },
    { name: 'Mexico - Tijuana', value: 'America/Tijuana' },
    { name: 'Barbados', value: 'America/Barbados' },
    { name: 'Belize', value: 'America/Belize' },
    { name: 'Brazil - Costa Rica', value: 'America/Costa_Rica' },
    { name: 'Cuba - Havana', value: 'America/Havana' },
    { name: 'Chile - Santo Domingo', value: 'America/Santo_Domingo' },
    { name: 'Mexico - El Salvador', value: 'America/El_Salvador' },
    { name: 'Guatemala', value: 'America/Guatemala' },
    { name: 'Haiti - Port-au-Prince', value: 'America/Port-au-Prince' },
    { name: 'Honduras - Tegucigalpa', value: 'America/Tegucigalpa' },
    { name: 'Cuba - Jamaica', value: 'America/Jamaica' },
    { name: 'Martinique', value: 'America/Martinique' },
    { name: 'Nicaragua - Managua', value: 'America/Managua' },
    { name: 'United States - Panama', value: 'America/Panama' },
    { name: 'Argentina - Puerto Rico', value: 'America/Puerto_Rico' },
    { name: 'Miquelon', value: 'America/Miquelon' },
    { name: 'Grand Turk', value: 'America/Grand_Turk' },
    {
      name: 'Argentina - Buenos Aires',
      value: 'America/Argentina/Buenos_Aires',
    },
    { name: 'Cordoba', value: 'America/Argentina/Cordoba' },
    { name: 'Argentina - Salta', value: 'America/Argentina/Salta' },
    { name: 'Tucuman', value: 'America/Argentina/Tucuman' },
    { name: 'Argentina - La Rioja', value: 'America/Argentina/La_Rioja' },
    { name: 'Argentina - San Juan', value: 'America/Argentina/San_Juan' },
    { name: 'Jujuy', value: 'America/Argentina/Jujuy' },
    { name: 'Catamarca', value: 'America/Argentina/Catamarca' },
    { name: 'Argentina - Mendoza', value: 'America/Argentina/Mendoza' },
    { name: 'Argentina - San Luis', value: 'America/Argentina/San_Luis' },
    { name: 'Rio Gallegos', value: 'America/Argentina/Rio_Gallegos' },
    { name: 'Argentina - Ushuaia', value: 'America/Argentina/Ushuaia' },
    { name: 'Argentina - La Paz', value: 'America/La_Paz' },
    { name: 'Noronha', value: 'America/Noronha' },
    { name: 'Mexico - Belem', value: 'America/Belem' },
    { name: 'Santarem', value: 'America/Santarem' },
    { name: 'Brazil - Fortaleza', value: 'America/Fortaleza' },
    { name: 'Brazil - Recife', value: 'America/Recife' },
    { name: 'Araguaina', value: 'America/Araguaina' },
    { name: 'Maceio', value: 'America/Maceio' },
    { name: 'Bahia', value: 'America/Bahia' },
    { name: 'Sao Paulo', value: 'America/Sao_Paulo' },
    { name: 'Argentina - Campo Grande', value: 'America/Campo_Grande' },
    { name: 'Cuiaba', value: 'America/Cuiaba' },
    { name: 'Brazil - Porto Velho', value: 'America/Porto_Velho' },
    { name: 'Brazil - Boa Vista', value: 'America/Boa_Vista' },
    { name: 'Brazil - Manaus', value: 'America/Manaus' },
    { name: 'Eirunepe', value: 'America/Eirunepe' },
    { name: 'Brazil - Rio Branco', value: 'America/Rio_Branco' },
    { name: 'Brazil - Santiago', value: 'America/Santiago' },
    { name: 'Chile - Punta Arenas', value: 'America/Punta_Arenas' },
    { name: 'United States - Bogota', value: 'America/Bogota' },
    { name: 'Ecuador - Guayaquil', value: 'America/Guayaquil' },
    { name: 'Cayenne', value: 'America/Cayenne' },
    { name: 'Guyana', value: 'America/Guyana' },
    { name: 'Peru - Asuncion', value: 'America/Asuncion' },
    { name: 'Peru - Lima', value: 'America/Lima' },
    { name: 'Suriname - Paramaribo', value: 'America/Paramaribo' },
    { name: 'United States - Montevideo', value: 'America/Montevideo' },
    { name: 'Venezuela - Caracas', value: 'America/Caracas' },
  ],
};
