export const SET_SIDEBAR_EXTENDED = 'SET_SIDEBAR_EXTENDED';
export const SET_ADVANCED_FILTERS = 'SET_ADVANCED_FILTERS';
export const SET_SHOW_MOBILE_MENU = 'SET_SHOW_MOBILE_MENU';
export const SET_LIMIT_TAGS = 'SET_LIMIT_TAGS';

export const SET_APPLICATION_SOURCE = 'SET_APPLICATION_SOURCE';
export const SET_APPLICATION_STATUS = 'SET_APPLICATION_STATUS';
export const SET_LEAD_FLOW_STATUS = 'SET_APPLICATION_STATUS';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_INDUSTRIES = 'SET_INDUSTRIES';
export const SET_STARTUP_VISIBILITY = 'SET_STARTUP_VISIBILITY';
export const SET_ASSIGNED_INVESTMENT_MANAGER =
  'SET_ASSIGNED_INVESTMENT_MANAGER';
export const SET_INVESTMENT_MANAGER_FILTER = 'SET_INVESTMENT_MANAGER_FILTER';
